/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Users.UserDirectory;

/**
 *
 * @author shaur
 */
public class PanelSignup extends javax.swing.JPanel {

    /**
     * Creates new form PanelSignup
     */
    UserDirectory ud;
    public PanelSignup(UserDirectory ud) {
        initComponents();
        this.ud = ud;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelSignupName = new javax.swing.JLabel();
        LabelSignupPhNo = new javax.swing.JLabel();
        LabelSignupEmail = new javax.swing.JLabel();
        LabelSignupCurrentAdd = new javax.swing.JLabel();
        LabelSignupPermAdd = new javax.swing.JLabel();
        TFSignupName = new javax.swing.JTextField();
        TFSignupPhNo = new javax.swing.JTextField();
        TFSignupEmail = new javax.swing.JTextField();
        TFSignupCurrAdd1 = new javax.swing.JTextField();
        TFSignupPermAdd1 = new javax.swing.JTextField();
        ButtonSignupSave = new javax.swing.JButton();
        LabelSingupPassword = new javax.swing.JLabel();
        LabelSignupUserName = new javax.swing.JLabel();
        TFSignupUsername = new javax.swing.JTextField();
        TFSignupPassword = new javax.swing.JTextField();
        LabelSignupTitle = new javax.swing.JLabel();

        LabelSignupName.setText("Full Name");

        LabelSignupPhNo.setText("Phone number");

        LabelSignupEmail.setText("E-mail Address");

        LabelSignupCurrentAdd.setText("Current Address");

        LabelSignupPermAdd.setText("Permanent Address");

        TFSignupName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        TFSignupCurrAdd1.setFont(new java.awt.Font("Bookman Old Style", 2, 11)); // NOI18N
        TFSignupCurrAdd1.setForeground(new java.awt.Color(204, 204, 204));
        TFSignupCurrAdd1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TFSignupCurrAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSignupCurrAdd1ActionPerformed(evt);
            }
        });

        ButtonSignupSave.setText("Save");
        ButtonSignupSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignupSaveActionPerformed(evt);
            }
        });

        LabelSingupPassword.setText("Password");

        LabelSignupUserName.setText("User Name");

        TFSignupUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        TFSignupPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        LabelSignupTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelSignupTitle.setText("Welcome to SpaceFinder ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LabelSignupPhNo)
                                .addComponent(LabelSignupName))
                            .addComponent(LabelSignupUserName)
                            .addComponent(LabelSingupPassword))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFSignupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFSignupUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFSignupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFSignupPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSignupTitle)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelSignupEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSignupEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelSignupCurrentAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSignupCurrAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(ButtonSignupSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelSignupPermAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSignupPermAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LabelSignupCurrentAdd, LabelSignupEmail, LabelSignupName, LabelSignupPermAdd, LabelSignupPhNo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TFSignupCurrAdd1, TFSignupEmail, TFSignupName, TFSignupPassword, TFSignupPermAdd1, TFSignupPhNo, TFSignupUsername});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelSignupTitle)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFSignupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSignupName))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelSignupUserName)
                    .addComponent(TFSignupUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSingupPassword)
                    .addComponent(TFSignupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSignupPhNo)
                    .addComponent(TFSignupPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSignupEmail)
                    .addComponent(TFSignupEmail))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSignupCurrentAdd)
                    .addComponent(TFSignupCurrAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSignupPermAdd)
                    .addComponent(TFSignupPermAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(ButtonSignupSave)
                .addGap(150, 150, 150))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFSignupCurrAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSignupCurrAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSignupCurrAdd1ActionPerformed

    private void ButtonSignupSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignupSaveActionPerformed
        // TODO add your handling code here
        String name = TFSignupName.getText();
        String uname = TFSignupUsername.getText();
        String pass = TFSignupPassword.getText();
        String pno = TFSignupPhNo.getText();
        String email = TFSignupEmail.getText();
        String cadd = TFSignupCurrAdd1.getText();
        String add = TFSignupPermAdd1.getText();
        ud.addUser(name, uname, pass, pno, add, cadd, email, "User");
    }//GEN-LAST:event_ButtonSignupSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSignupSave;
    private javax.swing.JLabel LabelSignupCurrentAdd;
    private javax.swing.JLabel LabelSignupEmail;
    private javax.swing.JLabel LabelSignupName;
    private javax.swing.JLabel LabelSignupPermAdd;
    private javax.swing.JLabel LabelSignupPhNo;
    private javax.swing.JLabel LabelSignupTitle;
    private javax.swing.JLabel LabelSignupUserName;
    private javax.swing.JLabel LabelSingupPassword;
    private javax.swing.JTextField TFSignupCurrAdd1;
    private javax.swing.JTextField TFSignupEmail;
    private javax.swing.JTextField TFSignupName;
    private javax.swing.JTextField TFSignupPassword;
    private javax.swing.JTextField TFSignupPermAdd1;
    private javax.swing.JTextField TFSignupPhNo;
    private javax.swing.JTextField TFSignupUsername;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
